"""change teacher schema

Revision ID: 0c599e46711a
Revises: 97e2275a9d34
Create Date: 2020-12-10 00:19:03.722416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c599e46711a'
down_revision = '97e2275a9d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_foreign_key('user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('first_name')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint('user_id', type_='foreignkey')

    # ### end Alembic commands ###
