"""empty message

Revision ID: 111a063575d2
Revises: 964b6f5bbd6e
Create Date: 2021-01-04 12:20:59.906136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111a063575d2'
down_revision = '964b6f5bbd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_model')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_model_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('faq_model_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('faq_model_id')
        batch_op.drop_column('doc_model_id')

    op.create_table('qa_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('model_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model_type', sa.VARCHAR(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
