"""empty message

Revision ID: 6ecfa6145ff9
Revises: 111a063575d2
Create Date: 2021-01-16 14:50:58.540256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecfa6145ff9'
down_revision = '111a063575d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_question_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_path', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_question_answer', schema=None) as batch_op:
        batch_op.drop_column('doc_path')

    # ### end Alembic commands ###
