"""empty message

Revision ID: 913348fc7fe8
Revises: aef6cb3cc5c4
Create Date: 2020-12-03 17:56:58.128288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913348fc7fe8'
down_revision = 'aef6cb3cc5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_materials', 'data')
    # ### end Alembic commands ###
