"""empty message

Revision ID: aef6cb3cc5c4
Revises: 450250f8182d
Create Date: 2020-12-03 17:46:29.259636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef6cb3cc5c4'
down_revision = '450250f8182d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_materials') as batch_op:
        batch_op.drop_column('content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('content', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
